### ISSUE TITLE
WARNING: Could not determine version of module x

### ISSUE THREAD

**Issue by axelblomberg** [liady/webpack-node-externals#103]
Error example in detail
`Serverless: Invoke webpack:package`
`Serverless: WARNING: Could not determine version of module arrify`

Hi. We have an issue where our root hoisted dependencies (using Lerna) cannot be resolved correctly when we bundle and `webpack:package` runs. This is causing the bundled package.json file to include referenced version as an empty string, see below.

`"dependencies": {`
`      "arrify": "",`
`    }`

The general issue with this is that dependencies are automatically resolved to latest version which can cause issues if there are breaking changes and so on.

I noticed that there were a version published 8 hours ago by @j0k3r where this functionality was included;

![image](https://user-images.githubusercontent.com/17126470/116433257-9e7cf380-a849-11eb-917b-e6e479e6c0d4.png)
 
However, this did not seem to do the trick. Anyone with similar issues using monorepo, serverless and serverless-webpack?

**Comment by axelblomberg** [comment]
Sorry, this was posted in the wrong github repo. Please remove.

**Comment by j0k3r** [comment]
It's not published, it has been merged. If you use the master of `serverless-webpack`, the option is avalaible. Otherwise it's not.
