### ISSUE TITLE
Entry with webpack/hot/poll?1000 isn't correctly treated as an external

### ISSUE THREAD

**Issue by ericclemmons** [liady/webpack-node-externals#11]
When I have something like:

```js
{
  entry: ["webpack/hot/poll?1000", "./src/client.js"],
  externals: [nodeExternals()],
}
```

I get an error from Webpack like:
> Module not found: webpack/hot/poll?1000

I tried forking the repo to demonstrate the problem, but had a difficult time working out the tests.

Let me know if this passes the sniff test for you, otherwise I'll do what I can to help.

Thanks!

**Comment by liady** [comment]
@ericclemmons did you try to adding it to the [whitelist](https://github.com/liady/webpack-node-externals#example)?

```
externals: [nodeExternals({
  whitelist: ['webpack/hot/poll?1000']
})]
```

**Comment by ericclemmons** [comment]
@liady I didn't, as was under the impression that it _shouldn't_ be bundled and instead referenced as an external.

So you're saying that this _should_ be bundled to work correctly?

**Comment by liady** [comment]
@ericclemmons Yes (only when using hot reload, of course). That's needed for it to work. 
In any case it shouldn't affect your production bundle, since it's not supposed to be built with hot-reload anyway.

**Comment by ericclemmons** [comment]
Ah, I see.  That's the trick then.  Thanks for the help!  I assumed that Webpack 2 know how to handle this entry point, but with the `?1000` it _has_ to parse it.
