### ISSUE TITLE
includes ./../../../node_modules/css-loader/lib/css-base.js when it shouldn't

### ISSUE THREAD

**Issue by gajus** [liady/webpack-node-externals#14]
`css-loader` [injects](https://github.com/webpack/css-loader/blob/22f6621a175e858bb604f5ea19f9860982305f16/lib/loader.js#L116) `./../../../node_modules/css-loader/lib/css-base.js` dependency.

This is considered an external dependency.

`webpack-node-externals` should not allow it.

**Comment by gajus** [comment]
It safe to say that anything that matches `/node_modules/` ought not to be included.

Adding directory separator to the regex might be a good idea too.

**Comment by liady** [comment]
@gajus thanks for the feedback.
Can you please pull the latest version (1.4.3) and check if setting the `includeAbsolutePaths` flag to `true` solves it?
```js
{
  externals: [nodeExternals({
    includeAbsolutePaths: true
  })]
}
```

As a default, the library sets as externals only the `require('moduleName')` references, but if the `includeAbsolutePaths` flag solves this issue (as it also take cares of complex paths) , I may insert it as true by default.

**Comment by liady** [comment]
@gajus is this still happening?

**Comment by gajus** [comment]
At the end, I had to include the relative paths into the bundle because of the issue described here, https://github.com/gajus/isomorphic-webpack/blob/1e776e0a9ff853363ba979e2a6072812b7174881/src/factories/createCompilerConfiguration.js#L20-L33.

> // @todo
> //
> // Relative resources are not being resolved, because 'require'
> // is relative to the path of the 'overrideRequire' and not to
> // the path of the original resource.

I am sure there is a workaround, though I haven't had a chance to look into it.

**Comment by cc-ebay** [comment]
@liady This is still an issue. Especially when a loader emits these kind of paths.
