### ISSUE TITLE
best way to not externalize assets?

### ISSUE THREAD

**Issue by wmertens** [liady/webpack-node-externals#15]
Sometimes you will be loading e.g. css files from an npm package, and those need to be converted so they cannot be external. This is what I came up with:

```js
			nodeExternals({
				// load non-javascript files with extensions, presumably via loaders
				whitelist: [/\.(?!(js|json)$).{1,5}$/i],
			}),
```

That assumes that anything that has a max-5-char extension but is not js or json, will need to be parsed as an internal module.

Is this the best way? If so, perhaps put it in the Readme?

**Comment by liady** [comment]
@wmertens Good idea. I added it to the Q&A section. Thanks!

**Comment by richardscarrott** [comment]
Hi @wmertens, good tip; out of interest, why do you avoid whitelisting files with an extension longer than 5 chars?

**Comment by wmertens** [comment]
Can't remember why I did that, and can't think of a reason ;)
Perhaps just replace it with `[^.]*`
