### ISSUE TITLE
Allow whitelisting of a module/subpath

### ISSUE THREAD

**Issue by slmgc** [liady/webpack-node-externals#2]
Hi, I have a use case:

```javascript
// This module is whitelisted in a config
import 'some_module'

// This one won't be whitelisted and needs
// to be added explicitly to the whitelist
import 'some_module/subpath/to/some_file' 
```

Is there some way to resolve this issue?

**Comment by liady** [comment]
Thanks!
Do you think that adding glob/regex support to the whitelist will suffice?

**Comment by slmgc** [comment]
Yeah, I think so, thank you!

**Comment by liady** [comment]
Added support for regex in the whitelist, so you can define:
```js
externals: [nodeExternals({
  whitelist: [/^some_module/]
})]
```
And it will white-list `some_module` and all `some_module/subpaths` from being bundled.

Let me know how that works for you.
