### ISSUE TITLE
Incorrectly classifies namespaced packages as external

### ISSUE THREAD

**Issue by lemonmade** [liady/webpack-node-externals#30]
My team has some packages that we bring in through npm namespaced under our organization (so, `@shopify/package-name`. We also have a local `packages` folder that contains packages we intend to release, but have not done so yet (so, `packages/@shopify/local-package-name`). Because of [this line](https://github.com/liady/webpack-node-externals/blob/master/index.js#L71), which considers only the first part of a module name for the purpose of checking its presence in `node_modules`, all of our local packages are treated as externals and not bundled (we want them to be bundled for now since they are basically "app code", and because we don't want to mess with the NODE_PATH at runtime to include `packages` as a require-able directory).

Let me know if I can provide more details. Thanks for the great tool!

**Comment by liady** [comment]
@lemonmade does version 1.6.0 solve it?

**Comment by lemonmade** [comment]
Yes, this does solve my issue. Thanks for addressing it so quickly!
