### ISSUE TITLE
whitelist regex/string question

### ISSUE THREAD

**Issue by chrisblossom** [liady/webpack-node-externals#33]
I've recently found an issue with a different library that required the library to be included with the webpack build. I was unable to use the exact string syntax, but instead needed a regex to work. 

Any thoughts of what could be the cause of this?

https://github.com/faceyspacey/react-universal-component/issues/3#issuecomment-307667250

**Comment by liady** [comment]
@chrisblossom Using a string in the whitelist array triggers an exact comparison of the required path. Meaning that setting `myModule` in the list **won't** whitelist `myModule/subModule`.

If in your case you needed `react-universal-component/*` to be whitelisted, indeed the regex `/^react-universal-component/` is the correct way to whitelist it.

**Comment by chrisblossom** [comment]
Thank you for your quick response!
