### ISSUE TITLE
ignore devDependencies

### ISSUE THREAD

**Issue by errorx666** [liady/webpack-node-externals#43]
When I put a dependency into `devDependencies` without `dependencies`, I'm intending to indicate "this module only needs to be installed to build my library."  My compiled library should not expect that the module is installed.

With the current behavior of `webpack-node-externals`, even if I specify `modulesFromFile`, any dependencies in `devDependencies` will not be bundled with my library, nor will they be installed by npm (unless the user explicitly opts-in to dev).  The result is a bundle that works in my dev environment, passes tests in dev, and fails when pushed out to users!

I expect `devDependencies` to be part of the bundle, not marked as externals.  If necessary (to avoid a breaking change), please make this a flag so I can opt-in to this behavior.

**Comment by liady** [comment]
Resolved in `1.7.0`:
https://github.com/liady/webpack-node-externals/blob/master/README.md#optionsmodulesfromfile-false
