### ISSUE TITLE
It throws an error if there's no `node_modules`

### ISSUE THREAD

**Issue by fabiospampinato** [liady/webpack-node-externals#44]
If the `process.cwd ()` doesn't contain a `node_modules` directory I get this error:

```javascript
{ Error: ENOENT: no such file or directory, scandir 'node_modules'
```

Usually it wouldn't make sense to use this package in a project that doesn't even have a `node_modules` directory, but I'm using this package as part of a larger program for bundling files, and I think there's no need to throw an error in this case.

**Comment by liady** [comment]
Resolve in `1.7.0`
