### ISSUE TITLE
utils not found

### ISSUE THREAD

**Issue by Falieson** [liady/webpack-node-externals#47]
```
Florians-MBP:collector falieson$ nps build.server
nps is executing `build.server` : npx webpack --config webpack/webpack.dev.server.js
Cannot find module './utils'
```

in my `node_modules/webpack-node-externals/index.js`
there is `var utils = require('./utils');`
but there is no utils in the folder

    "webpack-node-externals": "1.7.1",

**Comment by liady** [comment]
Correct. Fixed in `1.7.2`. Thanks!
