### ISSUE TITLE
New release 1.7.1 is breaking with this - Error: Cannot find module './utils'

### ISSUE THREAD

**Issue by tksumanth1994** [liady/webpack-node-externals#49]
<img width="997" alt="screenshot 2018-04-02 06 14 57" src="https://user-images.githubusercontent.com/4353562/38179136-30a449de-363d-11e8-94fe-d264dde116c4.png">
Not able to build files. Stops at this error. Please help. @liady

**Comment by tksumanth1994** [comment]
Edit: Issue with version 1.7.1

**Comment by liady** [comment]
@tksumanth1994, did `1.7.2` solve it for you?

**Comment by tksumanth1994** [comment]
Yes 👍

**Comment by AtlasMaxima** [comment]
This similar issue occurred with `1.7.0` but just updated to `1.7.2` and this issue was resolve :)
