### ISSUE TITLE
Can you please explain modulesFromFile config option?

### ISSUE THREAD

**Issue by demian85** [liady/webpack-node-externals#61]
I need to bundle explicit dependencies since I'm deploying to AWS Lambda. 
How can I specifically include all of my project _dependencies_ to be bundled and exclude all of my _devDependencies_ and native node modules?

Documentation [here](https://github.com/liady/webpack-node-externals#optionsmodulesfromfile-false) is not clear at all. Should I parse the package.json myself and extract the dependency names as an array of strings? 

Thanks.

**Comment by liady** [comment]
Since you need the `dependencies` to be bundled and the `devDependencies` not to be bundled - you actually need to tell the library to treat only the `devDependencies` as externals. Meaning:
```
modulesFromFile: {
        exclude: ['dependencies'],
        include: ['devDependencies']
    }
```
