### ISSUE TITLE
[Question] do I need to add exclude section to loaders with this library?

### ISSUE THREAD

**Issue by andykais** [liady/webpack-node-externals#63]
Hi, I have a broad question about how this library works. If I use `webpack-node-externals` like so:
```js
const nodeExternals = require('webpack-node-externals')
module.exports {
  ...
  externals: [nodeExternals()]
}
```

what does it actually do? The [webpack documentation](https://webpack.js.org/configuration/externals/) states
> The externals configuration option provides a way of excluding dependencies from the output bundles

What I want to know, is if this also prevents anything in the node_modules folder from reaching the loaders. A lot of loaders recommend adding an `exclude: /node_modules/` section to prevent node_modules from being transpiled (`babel-loader`, `awesome-typescript-loader`, `istanbul-instrumenter-loader`, etc). I want to know if this step is necessary provided we are already using `webpack-node-externals`.

**Comment by liady** [comment]
Yes, the loaders configuration is not affected by this plugin. This plugin merely prevents dependencies (i.e `node_modules`) from being bundled - and it is used mainly when bundling code as a node library.
(since in a node environment you do not need to bundle your dependencies)
