### ISSUE TITLE
modulesFromFile has no effect!

### ISSUE THREAD

**Issue by grapewheel** [liady/webpack-node-externals#69]
version: 1.7.2

webpack config
```js
externals: [
        nodeExternals({
            modulesFromFile: { // Or true
                exclude: ['devDependencies'],
                include: ['dependencies']
            }
        })
    ]
```
But still external all the modules

**Comment by liady** [comment]
@grapewheel do you need to actually bundle the `devDependencies`? Note that using the `modulesFromFile` is advisable only if the default setting (i.e getting the modules list from `node_modules`) do not work.

**Comment by liady** [comment]
@grapewheel @thiagotigaz note that you can use now `excludeFromBundle` and `includeInBundle` which might be clearer. Closing for now, let me know if the problem persists.
