### ISSUE TITLE
Include a warning when using whitelist instead of allowlist

### ISSUE THREAD

**Issue by mathieu-bour** [liady/webpack-node-externals#76]
I was reading the following article: https://medium.com/@amitdhawan_20991/part-2-packaging-nestjs-application-using-webpack-typescript-config-set-up-534a25a40a27

In this tutorial, there is a sample wepack.config.js which uses nodeExternals with the whitelist option.

```js
{
  // [...]
  externals: [
    nodeExternals({
      whitelist: ['webpack/hot/poll?100'],
    }),
  ],
  // [...]
}
```

While I am an enthusiast of the allowlist/denylist terms, I think that there should be a warning to tell the developer that he is not using the right option instead of silently ignoring the white-allowlist, which can be really confusing if you are not aware of this change.

**Comment by liady** [comment]
You're right, thank you. Added options validation and messages in version `2.4`.

**Comment by mathieu-bour** [comment]
For reference: 3b9069bb81cb832e2b2087234b67ec2339f70c1b
