### ISSUE TITLE
Docs. Changelog. 1.7.0 => 2.5.0

### ISSUE THREAD

**Issue by o-alexandrov** [liady/webpack-node-externals#77]
Could you please let us know what is the breaking change between 1.7.0 and 2.5.0?
I tried to locate a changelog, but don't see one.

**Comment by liady** [comment]
Yes, the `whitelist` has been renamed to `allowlist`. Seems like the changelog wasn't created, I will take a look.

**Comment by o-alexandrov** [comment]
Closing as Liad Yosef kindly made a new release.
Thank you :)
