### ISSUE TITLE
Error: [webpack-node-externals] : Option 'whitelist' is not supported. Did you mean 'allowlist'?

### ISSUE THREAD

**Issue by cha0s** [liady/webpack-node-externals#78]
Yo, like, I get that you thought this was a goodthought, but wouldn't it be nice to give people a little grace period with a deprecation warning before you straight up deprecate tons and tons of peoples' builds? 

This is irresponsible and should be considered a bug.

**Comment by cha0s** [comment]
At least, please consider reverting this change for the current **minor** revision, and pushing the API breaking change to a **major** revision. See: https://semver.org/

**Comment by liady** [comment]
@cha0s thank you for your feedback.
Indeed this breaking change was only introduced in major version 2.0.0 of the package.

**Comment by liady** [comment]
@cha0s did you manage to make it work on your side? Please let me know if you still have issues with it

**Comment by cha0s** [comment]
Thank you for asking. I was able to get it working. I hadn't noticed that the version was bumped in the first place, which was my embarrassing mistake. I will leave off the Fahrenheit 451 book report and am satisfied to close the issue, which I did.

**Comment by David00154** [comment]
how did you make it work?

**Comment by G-Freeman** [comment]
Есть ли решение?

**Comment by liady** [comment]
@G-Freeman do you still have an issue with the `allowlist` vs `whitelist`? Which version are you using? Note that the name was changes in v2.0.0
