### ISSUE TITLE
Option 'allowlist' is not supported. Did you mean 'allowlist'?

### ISSUE THREAD

**Issue by Darmody** [liady/webpack-node-externals#80]
Hi there! Did I miss anything?

![Screen Shot 2020-08-07 at 4 07 53 PM](https://user-images.githubusercontent.com/6788752/89624370-b631d780-d8c8-11ea-8551-4273e8a232f7.png)

**Comment by liady** [comment]
Seems weird. Maybe there's a hidden character there? Can you try and re-type `allowlist` as the key?

**Comment by liady** [comment]
@Darmody please update to v2.5.1, where this issue was fixed. Thank you so much.

**Comment by Darmody** [comment]
@liady Thanks! Have a good day!
