### ISSUE TITLE
Mention WebPack 5 externalsPresets option in readme

### ISSUE THREAD

**Issue by david-fong** [liady/webpack-node-externals#88]
(This is just a suggestion).

WebPack v5 has added a new option called [`externalsPresets`](https://webpack.js.org/configuration/externals/#externalspresets). The `"node"` setting is probably what most people will want to use for code that will only run on the NodeJS runtime. For people who are new to WebPack and who find this package, it may be helpful to them to mention that they don't need this plugin for such a use-case.

**Comment by liady** [comment]
@david-fong thanks for this suggestion. Actually the `externalsPreset: node` will only externalize the **built in** packages of node, and not the installed mode modules themselves.
If you'll look at the official [Webpack documentation](https://webpack.js.org/configuration/externals/#function) you can actually see that this plug-in is recommended for externalizing node modules.
The `externalsPreset` only replaces the `target` key in the config in that sense, and not the externals mechanism.
Thanks again for the suggestion.
