### ISSUE TITLE
Is this needed for Webpack @ 2?

### ISSUE THREAD

**Issue by sjmcdowall** [liady/webpack-node-externals#9]
I am using the beta version of Webpack V2.  Just wondering if this is still needed with that or did they build something in to do this?  My gut says its still needed, because I haven't figured out a way around it yet. :)

**Comment by liady** [comment]
@sjmcdowall Good question. From what I know about Webpack v2, there still isn't a good solution for not bundling node modules. I will keep investigate, and update if I learn anything different.
